<?php

/**
 * PluginsbEnhancedSearchPhraseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEnhancedSearchPhraseTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginsbEnhancedSearchPhraseTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('PluginsbEnhancedSearchPhrase');
  }
  
  public static function cleanPhrase($phrase)
  {
    return $phrase;
  }
  
  public static function getPhrases()
  {
    return array('Test1', 'Test2', 'Test3');
  }
}