<?php

/**
 * PluginaProjectPageToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaProjectPageToCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaProjectPageToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaProjectPageToCategory');
    }
}