<?php

/**
 * PluginsbEnhancedSearchPhraseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEnhancedSearchPhraseTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginsbEnhancedSearchPhraseTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('PluginsbEnhancedSearchPhrase');
  }
  
  public static function cleanPhrase($phrase)
  {
    $phrase = strtolower($phrase);
    return $phrase;
  }
  
  public static function cleanPhraseForDisplay($phrase)
  {
    $phrase = ucfirst($phrase);
    return $phrase;
  }
  
  public static function getPhrases($term = null)
  {
    $results = array();
    
    $root = $root = Doctrine_Query::create()
						->select('phrase')
						->from('sbEnhancedSearchPhrase');
    
    if($term != null and $term != '' and strlen($term) > 1)
		{
			$root->where('phrase LIKE ?', '%' . self::cleanPhrase($term) . '%');
		}
    
    $root->andWhere('last_number_results > 0');
    
    $root->groupBy('phrase');
		$root->orderBy('usage_count, last_number_results');

		$phrases = $root->execute(array(), Doctrine::HYDRATE_ARRAY);
		foreach($phrases as $phrase){ $results[$phrase['phrase']] = self::cleanPhraseForDisplay($phrase['phrase']); }
		return $results;
  }
}