<?php

/**
 * PluginsbExternalLinkClickTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbExternalLinkClickTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbExternalLinkClickTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbExternalLinkClick');
    }
}