# Routes for Enhanced Search
sb_enhanced_search:
  url: /admin/a/enhanced-search
  param: { module: sbEnhancedSearch, action: search }
sb_enhanced_search_terms:
  url: /admin/a/enhanced-search-terms
  param: { module: sbEnhancedSearch, action: terms }
  
# Routes for External Link Tracking
sb_external_link_click_save:
  url: /admin/sb-external-link-click-save
  param: { module: sbExternalLinkClick, action: save }